spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/books
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 32
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    root: info
server:
  port: 8889

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://34.85.73.209:3308/books
  jpa:
    show-sql: false