spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/books
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 64
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL8Dialect
  profiles:
    active: dev

logging:
  level:
    root: info
server:
  port: 8889

thread-pool:
  common-core-pool-size: 24
  common-max-pool-size: 32
  content-core-pool-size: 24
  content-max-pool-size: 32
sync:
  syncPage: 1
---
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://34.85.73.209:3308/books